### ISSUE TITLE
Charles上弄好了怎么导出到网球上用？

### ISSUE THREAD

**Issue by dicock** [yukerui/lovecxl#18]
Charles上弄好了怎么导出到网球上用？

**Comment by yukerui** [comment]
看下这个里面[网球规则合集](https://github.com/yukerui/httpCatcher-rules)

**Comment by yukerui** [comment]
一般是通过charles找接口和修改值，找到之后直接到网球里找到对应接口然后新建就好

**Comment by dicock** [comment]
> 一般是通过charles找接口和修改值，找到之后直接到网球里找到对应接口然后新建就好

这样啊！谢谢！
